# Generated by Django 4.2.11 on 2024-03-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='empid',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
