# Generated by Django 4.2.11 on 2024-03-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_remove_staff_id_alter_staff_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='EmpId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
