# Generated by Django 4.2.11 on 2024-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_alter_staff_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, default=1200, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='EmpId',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
