# Generated by Django 4.2.11 on 2024-03-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_staff_id_alter_staff_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff',
            name='EmpId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
