# Generated by Django 4.2.11 on 2024-04-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsubjectassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubjectassignment',
            unique_together={('student',)},
        ),
    ]
