# Generated by Django 4.2.11 on 2024-04-01 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_remove_staff_id_alter_staff_empid'),
        ('corecode', '0005_subject_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.staff'),
        ),
    ]
