# Generated by Django 4.2.11 on 2024-04-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_invoice_options_remove_invoice_session_and_more'),
        ('result', '0002_remove_result_session_remove_result_term'),
        ('corecode', '0006_alter_subject_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicSession',
        ),
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
    ]
